### ISSUE TITLE
Please add padding to the top navigation

### ISSUE THREAD

**Issue by olawale-o** [Munsa1/Mobile-Version#3]
**Add padding to the top navigation**

![top_navigation](https://user-images.githubusercontent.com/55432600/121143989-7f548700-c835-11eb-8c51-f5dd6061d372.png)

**Comment by Munsa1** [comment]
I have solved this issue although it didn't require me to use padding but rather to add box-sizing to all. Check out my code and review it, please😊
Good day

**Comment by Munsa1** [comment]
Taken care of, thank you.
